# Generated by Django 3.2.5 on 2021-08-12 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WallPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='main/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user_info')),
            ],
        ),
    ]
