# Generated by Django 3.2.5 on 2021-08-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpaper',
            name='image',
            field=models.ImageField(blank=True, default='/board/static/image/lock-icon.jpg', null=True, upload_to='main/'),
        ),
    ]
