# Generated by Django 3.2.5 on 2021-08-12 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('board', '0003_alter_wallpaper_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpaper',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.user_info'),
        ),
    ]
