# Generated by Django 3.2.5 on 2021-08-07 17:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.storewidget')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user_info')),
            ],
        ),
    ]
