# Generated by Django 3.2.5 on 2021-08-08 15:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('store', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='widget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='store.storewidget'),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.comment')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user_info')),
            ],
        ),
    ]
