# Generated by Django 3.2.5 on 2021-08-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210809_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='storewidget',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='storewidgets/'),
        ),
        migrations.AlterField(
            model_name='storewidget',
            name='widget_type',
            field=models.CharField(choices=[('simple_widget_search_bar', '검색창'), ('layout_widget', '레이아웃 위젯')], default='layout_widget', help_text='위젯 형식', max_length=31),
        ),
    ]
