# Generated by Django 3.2.5 on 2021-08-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210809_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storewidget',
            name='widget_type',
            field=models.CharField(choices=[('simple_widget_search_bar', '검색창'), ('simple_widget_d_day', '디데이'), ('simple_widget_note', '메모장'), ('simple_widget_finance', '주식'), ('simple_widget_book_mark', '북마크'), ('layout_widget', '레이아웃 위젯')], default='layout_widget', help_text='위젯 형식', max_length=31),
        ),
    ]
