# Generated by Django 3.2.5 on 2021-08-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='name',
            field=models.CharField(blank=True, max_length=31),
        ),
    ]
