# Generated by Django 3.2.5 on 2021-08-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0002_layout_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='layouts/'),
        ),
    ]
