# Generated by Django 3.2.5 on 2021-08-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0003_layout_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='is_widget',
            field=models.BooleanField(default=False),
        ),
    ]
