# Generated by Django 3.2.5 on 2021-08-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0004_layout_is_widget'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='widget_type',
            field=models.TextField(null=True),
        ),
    ]
