# Generated by Django 3.2.5 on 2021-08-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('user_seq', models.AutoField(primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=255, verbose_name='user_email')),
                ('user_name', models.CharField(max_length=30, verbose_name='user_name')),
                ('user_pwd', models.CharField(max_length=512, verbose_name='user_pwd')),
                ('register_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
