# Generated by Django 3.2.5 on 2021-07-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('user_seq', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('user_email', models.EmailField(max_length=255)),
                ('user_password', models.TextField()),
                ('register_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
