# Generated by Django 3.2.5 on 2021-07-28 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_info',
            old_name='user_password',
            new_name='user_pwd',
        ),
    ]
